name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --workspace --tests -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run Rust tests
      run: cargo test --verbose
    - name: Install weechat
      run: sudo apt-get install -y weechat-headless
    - name: Run integration test
      run: tests/test.sh
